### ISSUE TITLE
Error: network.optimize_investment(invest_options=invest_opt)

### ISSUE THREAD

**Issue by okocak95** [oemof-heat/district_heating_simulation#139]
Hi all,

when i try to run the following code:
network.optimize_investment(invest_options=invest_opt)

i get this error:
TypeError: Node.init() got an unexpected keyword argument 'heat_loss_factor'

Can you please help me to find a solution?

Best regards,
Orcun

**Comment by sebber9** [comment]
I got the same error. Running the same code on Branch **Fix/oemof-network-0-5-0** works for me.

**Comment by susannehoch** [comment]
Hi,

I'm getting the same error but unfortunatley it can't be fixed by changing the version of oemof-network-0-5-0.. have you already solved your problem?

Best regards, Susanne

**Comment by okocak95** [comment]
Hi, 
yes it worked for me. what error are you getting exactly ? 

BG , Kocak

**Comment by p-snft** [comment]
The branch has been merged into dev, so I consider this fixed.
